### ISSUE TITLE
Error in QuoteSender.php

### ISSUE THREAD

**Issue by dnyt84** [beebots/magento2-admin-customer-quote#1]
Hello,

when I run php bin/magento setup:di:compile

I get the following error:

[@vz04 magento]$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/8 [===>------------------------]  12% 1 sec 80.5 MiB
Parse error: syntax error, unexpected ')' in magento/app/code/BeeBots/AdminCustomerQuote/Model/QuoteSender.php on line 98

I removed the , in line 97 and ran the command again and it worked.
I was able to send a Quote via email

Thank you

Daniel

**Comment by shilpsauce** [comment]
Should be fixed. now.
